### ISSUE TITLE
Position 'Search Fields' in the 'Content' section of JSON file

### ISSUE THREAD

**Issue by Peteer98** [CoLRev-Environment/search-query#10]
I found out that sometimes the field ‘Search Fields’ appears in the JSON files.

In Haddaway, 2022, the following is said about the Search Fields field: ‘Can be populated automatically from search history export. Optional if this is specified in the search string itself'.

However, this is not always the case, it can also happen that the ‘Search Fields’ field exists, but no search fields have been defined in the ‘Search’ field.

@k-schnickmann @ThomasFleischmann
Have you also noticed this?
Do you have any suggestions on how we should deal with it?

Suggestion from @geritwagner 
From the user's point of view, it might be helpful to receive the parsed query before the SearchField translation or to call it explicitly (optional).

**Comment by geritwagner** [comment]
I will try to clarify the different cases that could happen. The `search_field` can be empty, or contain a value, which match or contradict the SearchField specified in the `search_string`. These cases should be handled with appropriate user notifications.

For each of the following cases, a different response of the SearchQuery parser would be appropriate (suggestions):

| **Search-Field required**  | **Search String**      | **Search-Field**             | **Implications/Actions**                                                 |
|----------------------------|------------------------|------------------------------|--------------------------------------------------------------------------|
| Yes                        | With Search-Field      | Empty                        | ok                                                                       |
| Yes                        | With Search-Field      | Equal to Search-String       | ok - with warning: data redudancy                                        |
| Yes                        | With Search-Field      | Different from Search-String | error: contradiction in search fields                                    |
| Yes                        | Without Search-Field   | Empty                        | error: search field missing                                              |
| Yes                        | Without Search-Field   | Given                        | ok - with warning: recommend to specify search-field in search string    |
| No                         | With Search-Field      | Empty                        | ok                                                                       |
| No                         | With Search-Field      | Equal to Search-String       | ok - with warning: data redudancy                                        |
| No                         | With Search-Field      | Different from Search-String | error: contradiction in search fields                                    |
| No                         | Without Search-Field   | Empty                        | ok - with warning: recommend to specify search field explicitly          |
| No                         | Without Search-Field   | Given                        | ok - with warning: recommend to specify search-field in search string    |

Notes:

- If a SearchField is not required by a database, a predefined field is used per default.
- Passing SearchField separately to the parser should be optional.
- The case `empty` could be "SearchField not passed to parser" or "Empty SearchField passed to parser".

@Peteer98, @k-schnickmann and @ThomasFleischmann, please have a look at it and let us know whether you agree or propose changes.

**Comment by ThomasFleischmann** [comment]
Hello, @Peteer98 , @k-schnickmann and me had a meeting this week and we agree with the suggestion. 

Additionally, we discussed to differentiate between a strict and non-strict way. If the user chooses strict and there is an issue with the search field, for example:

-  if it is required but not there, 
- a not supportet search field 
- one SearchField and one in the search term itself, 

then the user should be prompted to make corrections to the string. 
If non-strict, the parser automatically adds/translates/chooses an appropriate search field value.

**Comment by geritwagner** [comment]
Thank you - this is a good point! I tried to summarize how that could be explained in the documentation. Please check and suggest clarifications.

## Parser modes

Strict mode: Forces the user to maintain clean, valid input but at the cost of convenience.

- Fails on fatal or error outcomes. Prints warnings.

Non-strict mode: Focuses on usability, automatically resolving common issues while maintaining transparency via warnings.

- Fails only on fatal outcomes. Auto-corrects errors as much as possible and prints a message (adds a fatal message if this is not possible). Prints warnings.

An additional "silent" option may be used to silence warnings.

## Messages

The parser/linter can add different messages (level: fatal, error, warning). Initial examples for the messages are:

Fatal

- tokenizing-failed (F0001)
- unbalanced-parentheses (F0002)
- missing-operator (F0003)

Error

- search-field-contradiction (E0001)
- search-field-missing (E0002)

Warning

- search-field-redundant (W0001), description: recommend specifying search-field in the search string only
- search-field-extracted (W002), description: recommend specifying search-field in the search string
- search-field-not-specified (W003), description: search-field should be specified explicitly


## Search Field Validation in Strict vs. Non-Strict Modes

| **Search-Field required**  | **Search String**      | **Search-Field**             | **Mode: Strict**                        | **Mode: Non-Strict**                                                          |
|----------------------------|------------------------|------------------------------|-----------------------------------------|-------------------------------------------------------------------------------|
| Yes                        | With Search-Field      | Empty                        | ok                                      | ok                                                                            |
| Yes                        | With Search-Field      | Equal to Search-String       | ok - search-field-redundant             | ok                                                                            |
| Yes                        | With Search-Field      | Different from Search-String | error: search-field-contradiction       | ok - search-field-contradiction. Parser uses Search-String per default        |
| Yes                        | Without Search-Field   | Empty                        | error: search-field-missing             | ok - search-field-missing. Parser adds `title` as the default                 |
| Yes                        | Without Search-Field   | Given                        | ok - search-field-extracted             | ok                                                                            |
| No                         | With Search-Field      | Empty                        | ok                                      | ok                                                                            |
| No                         | With Search-Field      | Equal to Search-String       | ok - search-field-redundant             | ok                                                                            |
| No                         | With Search-Field      | Different from Search-String | error: search-field-contradiction       | ok - search-field-contradiction. Parser uses Search-String per default        |
| No                         | Without Search-Field   | Empty                        | ok - search-field-not-specified         | ok - Parser uses default of database                                          |
| No                         | Without Search-Field   | Given                        | ok - search-field-extracted             | ok                                                                            |

**Comment by geritwagner** [comment]
I just added the overview to the documentation: [here](https://colrev-environment.github.io/search-query/dev_docs/linter.html) and I also added the `search-field-unsupported` error as suggested.
